version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run:
          name: Run unit tests
          command: goveralls -package=./... -v -race -covermode=atomic -service=circle-ci
